package com.company.orderapi.integration;

import org.springframework.test.context.TestPropertySource;

import com.company.orderapi.domain.Customer;
import com.company.orderapi.domain.Order;
import com.company.orderapi.domain.OrderStatus;
import com.company.orderapi.domain.Payment;
import com.company.orderapi.domain.PaymentMethod;
import com.company.orderapi.domain.PaymentStatus;
import jakarta.persistence.EntityManager;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.springframework.transaction.annotation.Transactional;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.math.BigDecimal;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * PR #13 integration tests: JPA lifecycle callbacks.
 *
 * <ul>
 *   <li>{@code @PrePersist} on Order - generates the order number once</li>
 *   <li>{@code @PreUpdate} on Payment - stamps the processed date</li>
 *   <li>{@code @PreRemove} on Customer - refuses deletion while orders exist</li>
 *   <li>{@code @PostLoad} on BaseEntity - observable load flag + logging</li>
 * </ul>
 */
@Testcontainers
@SpringBootTest
@TestPropertySource(properties = {
        "integration.database.tag=LifecycleCallbackIntegrationTest",
        "spring.jpa.properties.hibernate.cache.use_second_level_cache=false"
})
@Transactional
class LifecycleCallbackIntegrationTest {

    @Container
    @ServiceConnection
    static final PostgreSQLContainer<?> POSTGRES =
            new PostgreSQLContainer<>("postgres:16-alpine");

    @Autowired
    private EntityManager em;

    @Test
    void prePersistGeneratesAnOrderNumberExactlyOnce() {
        Customer customer = new Customer("cb1@example.com", "Callback One");
        Order order = new Order(customer, OrderStatus.PLACED, new BigDecimal("10.00"));
        customer.addOrder(order);
        em.persist(customer);
        em.flush();

        // Generated by @PrePersist before the INSERT.
        assertThat(order.getOrderNumber()).startsWith("ORD-").hasSize(14);

        // Stored, not just set in memory.
        String stored = (String) em.createNativeQuery(
                        "SELECT order_number FROM orders WHERE id = ?1")
                .setParameter(1, order.getId())
                .getSingleResult();
        assertThat(stored).isEqualTo(order.getOrderNumber());

        // An UPDATE must NOT regenerate it (number stays stable for life).
        order.setStatus(OrderStatus.CONFIRMED);
        em.flush();
        assertThat(order.getOrderNumber()).isEqualTo(stored);
    }

    @Test
    void preUpdateStampsTheProcessedDateOnPayment() {
        Customer customer = new Customer("cb2@example.com", "Callback Two");
        Order order = new Order(customer, OrderStatus.PLACED, new BigDecimal("20.00"));
        Payment payment = new Payment(order, new BigDecimal("20.00"), PaymentMethod.CREDIT_CARD);
        order.setPayment(payment);
        customer.addOrder(order);
        em.persist(customer);
        em.flush();

        // Still PENDING -> no date yet.
        assertThat(payment.getPaymentDate()).isNull();

        // Processing triggers an UPDATE; @PreUpdate stamps the date.
        payment.setStatus(PaymentStatus.PROCESSED);
        em.flush();
        assertThat(payment.getPaymentDate()).isNotNull();
    }

    @Test
    void preRemoveRefusesToDeleteACustomerWithOrders() {
        Customer customer = new Customer("cb3@example.com", "Callback Three");
        customer.addOrder(new Order(customer, OrderStatus.PLACED, new BigDecimal("5.00")));
        em.persist(customer);
        em.flush();

        assertThatThrownBy(() -> {
            em.remove(customer);
            em.flush();
        })
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("cannot be removed")
                .hasMessageContaining("order(s)");
    }

    @Test
    void postLoadFiresWhenAnEntityIsReadFromTheDatabase() {
        Customer customer = new Customer("cb4@example.com", "Callback Four");
        em.persist(customer);
        em.flush();
        long id = customer.getId();

        // A brand-new (never-loaded) instance has not fired the callback.
        assertThat(customer.isPostLoadFired()).isFalse();

        em.clear(); // drop the persistence context -> next read comes from DB
        Customer reloaded = em.find(Customer.class, id);
        assertThat(reloaded.isPostLoadFired())
                .as("@PostLoad fires on every database load")
                .isTrue();
    }
}
