--liquibase formatted sql

-- ============================================================================
-- PR #2 - Database Schema with Foreign Keys (Liquibase)
-- ----------------------------------------------------------------------------
-- One changeset per table so each change can be rolled back independently.
-- Foreign keys are defined AT THE DATABASE LEVEL (not only in JPA) because the
-- database is the last line of defence for data integrity - application bugs
-- and direct SQL can never corrupt the referential structure.
--
-- Delete-rule decisions (mirrors the spec):
--   CASCADE  : owner gone -> children gone (customers->orders/addresses)
--   RESTRICT : refuse deletion while references exist (products/categories)
--   SET NULL : keep the order, drop the reference (addresses on orders)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. customers  (no FK - root of the graph)
-- ----------------------------------------------------------------------------
--changeset sushant:2-create-customers
CREATE TABLE customers (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- email is a natural key: business-unique AND a login handle.
    email         VARCHAR(255) NOT NULL,
    full_name     VARCHAR(255) NOT NULL,
    phone_number  VARCHAR(50),
    CONSTRAINT uq_customers_email UNIQUE (email)
);
--rollback DROP TABLE IF EXISTS customers;

-- ----------------------------------------------------------------------------
-- 2. products  (no FK - root of the graph)
-- ----------------------------------------------------------------------------
--changeset sushant:2-create-products
CREATE TABLE products (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    description     TEXT,
    price           NUMERIC(19, 2) NOT NULL,
    stock_quantity  INTEGER NOT NULL DEFAULT 0,
    -- money/stock must never go negative at the database level
    CONSTRAINT ck_products_price_non_negative      CHECK (price >= 0),
    CONSTRAINT ck_products_stock_non_negative      CHECK (stock_quantity >= 0)
);
--rollback DROP TABLE IF EXISTS products;

-- ----------------------------------------------------------------------------
-- 3. categories  (no FK - root of the graph)
-- ----------------------------------------------------------------------------
--changeset sushant:2-create-categories
CREATE TABLE categories (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    description  TEXT,
    CONSTRAINT uq_categories_name UNIQUE (name)
);
--rollback DROP TABLE IF EXISTS categories;

-- ----------------------------------------------------------------------------
-- 4. addresses  -> customers (1:N)  ON DELETE CASCADE
-- ----------------------------------------------------------------------------
--changeset sushant:2-create-addresses
CREATE TABLE addresses (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id   BIGINT NOT NULL,
    street        VARCHAR(255) NOT NULL,
    city          VARCHAR(100) NOT NULL,
    state         VARCHAR(100),
    postal_code   VARCHAR(20),
    country       VARCHAR(100) NOT NULL,
    is_default    BOOLEAN NOT NULL DEFAULT FALSE,
    address_type  VARCHAR(32) NOT NULL DEFAULT 'HOME',
    -- CASCADE: a customer's addresses are meaningless once the customer is gone.
    CONSTRAINT fk_addresses_customer
        FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE
);
--rollback DROP TABLE IF EXISTS addresses;

-- ----------------------------------------------------------------------------
-- 5. orders  -> customers (CASCADE), -> addresses x2 (SET NULL)
-- ----------------------------------------------------------------------------
--changeset sushant:2-create-orders
CREATE TABLE orders (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id          BIGINT NOT NULL,
    order_date           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status               VARCHAR(32) NOT NULL,
    total_amount         NUMERIC(19, 2) NOT NULL,
    shipping_address_id  BIGINT,
    billing_address_id   BIGINT,
    -- The two addresses are *snapshots of the relationship*, not the customer's
    -- whole address book: deleting an address must NOT delete the order, it
    -- simply unlinks it -> SET NULL.
    CONSTRAINT fk_orders_customer
        FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE,
    CONSTRAINT fk_orders_shipping_address
        FOREIGN KEY (shipping_address_id) REFERENCES addresses (id) ON DELETE SET NULL,
    CONSTRAINT fk_orders_billing_address
        FOREIGN KEY (billing_address_id) REFERENCES addresses (id) ON DELETE SET NULL,
    -- Status values mirror the domain events (OrderPlaced/Confirmed/Shipped/
    -- Delivered/Cancelled). Keeping the list in the DB makes bad states
    -- impossible even for hand-written SQL.
    CONSTRAINT ck_orders_status
        CHECK (status IN ('PLACED', 'CONFIRMED', 'SHIPPED', 'DELIVERED', 'CANCELLED')),
    CONSTRAINT ck_orders_total_non_negative CHECK (total_amount >= 0)
);
-- ----------------------------------------------------------------------------
-- 6. order_items -> orders (CASCADE), -> products (RESTRICT)
-- ----------------------------------------------------------------------------
--changeset sushant:2-create-order-items
CREATE TABLE order_items (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT NOT NULL,
    product_id   BIGINT NOT NULL,
    quantity     INTEGER NOT NULL,
    unit_price   NUMERIC(19, 2) NOT NULL,
    total_price  NUMERIC(19, 2) NOT NULL,
    -- CASCADE: items belong to exactly one order - no orphans.
    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
    -- RESTRICT: never delete a product that is referenced by an order line.
    -- Historical orders must stay intact even when a product is discontinued.
    CONSTRAINT fk_order_items_product
        FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE RESTRICT,
    CONSTRAINT ck_order_items_quantity_positive   CHECK (quantity > 0),
    CONSTRAINT ck_order_items_unit_price_non_neg  CHECK (unit_price >= 0),
    CONSTRAINT ck_order_items_total_non_negative  CHECK (total_price >= 0)
);
--rollback DROP TABLE IF EXISTS order_items;

-- ----------------------------------------------------------------------------
-- 7. product_categories  (join table for Product <-> Category many-to-many)
-- ----------------------------------------------------------------------------
--changeset sushant:2-create-product-categories
CREATE TABLE product_categories (
    product_id   BIGINT NOT NULL,
    category_id  BIGINT NOT NULL,
    -- Composite primary key doubles as the index for product_id lookups AND
    -- prevents duplicate (product, category) rows.
    CONSTRAINT pk_product_categories PRIMARY KEY (product_id, category_id),
    CONSTRAINT fk_product_categories_product
        FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE RESTRICT,
    CONSTRAINT fk_product_categories_category
        FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE RESTRICT
);
--rollback DROP TABLE IF EXISTS product_categories;

-- ----------------------------------------------------------------------------
-- 8. payments -> orders (1:1, CASCADE)
-- ----------------------------------------------------------------------------
--changeset sushant:2-create-payments
CREATE TABLE payments (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         BIGINT NOT NULL,
    amount           NUMERIC(19, 2) NOT NULL,
    payment_method   VARCHAR(32) NOT NULL,
    status           VARCHAR(32) NOT NULL,
    transaction_id   VARCHAR(255),
    payment_date     TIMESTAMP,
    -- 1 order = 1 payment (see domain model). The UNIQUE constraint both
    -- enforces the 1:1 rule and indexes order_id for FK lookups.
    CONSTRAINT uq_payments_order_id UNIQUE (order_id),
    CONSTRAINT fk_payments_order
        FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT ck_payments_amount_non_negative CHECK (amount >= 0)
);
--rollback DROP TABLE IF EXISTS payments;

-- ----------------------------------------------------------------------------
-- Indexes on every foreign-key column.
-- ----------------------------------------------------------------------------
-- WHY: a FK column is only useful if lookups on it are fast. Without an index,
-- deleting a parent row forces a full table scan of every child table to check
-- the constraint (and any join on that column is slow). This is one of the
-- most common production performance mistakes.
--
-- Deliberately NOT indexed here:
--   * product_categories.product_id  - already the leading column of the PK
--   * payments.order_id              - already indexed by the UNIQUE constraint
-- Adding duplicate indexes would just waste disk and slow writes.
--changeset sushant:2-create-fk-column-indexes
CREATE INDEX idx_addresses_customer_id          ON addresses (customer_id);
CREATE INDEX idx_orders_customer_id             ON orders (customer_id);
CREATE INDEX idx_orders_shipping_address_id     ON orders (shipping_address_id);
CREATE INDEX idx_orders_billing_address_id      ON orders (billing_address_id);
CREATE INDEX idx_order_items_order_id           ON order_items (order_id);
CREATE INDEX idx_order_items_product_id         ON order_items (product_id);
CREATE INDEX idx_product_categories_category_id ON product_categories (category_id);
--rollback DROP INDEX IF EXISTS idx_addresses_customer_id;
--rollback DROP INDEX IF EXISTS idx_orders_customer_id;
--rollback DROP INDEX IF EXISTS idx_orders_shipping_address_id;
--rollback DROP INDEX IF EXISTS idx_orders_billing_address_id;
--rollback DROP INDEX IF EXISTS idx_order_items_order_id;
--rollback DROP INDEX IF EXISTS idx_order_items_product_id;
--rollback DROP INDEX IF EXISTS idx_product_categories_category_id;

