--liquibase formatted sql

-- ============================================================================
-- PR #19 - Event store table (append-only log for event sourcing).
-- ----------------------------------------------------------------------------
-- Metadata columns (aggregate/version/type/time) plus a payload holding the
-- serialised JSON event (stored as TEXT - the application serialises/parses it;
-- a JSONB column would require driver-level casts that complicate JPA writes).
-- The UNIQUE (aggregate_id, version) constraint is the heart of event sourcing:
-- a version can only ever be written once, so replays are deterministic.
-- ============================================================================

--changeset sushant:19-create-event-store
CREATE TABLE event_store (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_id    UUID NOT NULL,
    aggregate_type  VARCHAR(64) NOT NULL,
    event_type      VARCHAR(64) NOT NULL,
    version         INTEGER NOT NULL,
    occurred_at     TIMESTAMP NOT NULL,
    payload         TEXT NOT NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_event_store_aggregate_version UNIQUE (aggregate_id, version)
);
--rollback DROP TABLE IF EXISTS event_store;

--changeset sushant:19-index-event-store-aggregate
CREATE INDEX idx_event_store_aggregate_id ON event_store (aggregate_id);
--rollback DROP INDEX IF EXISTS idx_event_store_aggregate_id;
