--liquibase formatted sql

-- ============================================================================
-- PR #24 - idempotency keys table.
-- ----------------------------------------------------------------------------
-- A client sends Idempotency-Key on risky writes (order placement). The first
-- request stores the resulting status+body under that key; retries with the
-- SAME key replay the stored response instead of executing the write again.
-- ============================================================================

--changeset sushant:24-create-idempotency-keys
CREATE TABLE idempotency_keys (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key VARCHAR(64) NOT NULL,
    http_method     VARCHAR(10) NOT NULL,
    request_path    VARCHAR(255) NOT NULL,
    response_status INTEGER NOT NULL,
    response_body   TEXT NOT NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_idempotency_keys_key UNIQUE (idempotency_key)
);
--rollback DROP TABLE IF EXISTS idempotency_keys;
