--liquibase formatted sql

-- ============================================================================
-- PR #27 - compliance audit trail (GDPR accountability).
-- ----------------------------------------------------------------------------
-- Records WHO did WHAT to WHICH customer and WHEN. No foreign key on purpose:
-- an erasure must be auditable AFTER the customer row is gone. The detail
-- column holds non-PII JSON facts only (counts/modes) - raw personal data is
-- never written here, because GDPR applies to the audit trail as well.
-- ============================================================================

--changeset sushant:27-create-audit-log
CREATE TABLE audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    action      VARCHAR(64)  NOT NULL,
    actor       VARCHAR(255) NOT NULL,
    detail      TEXT,
    occurred_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--rollback DROP TABLE IF EXISTS audit_log;

--changeset sushant:27-index-audit-log-customer
CREATE INDEX idx_audit_log_customer_id ON audit_log (customer_id);
--rollback DROP INDEX IF EXISTS idx_audit_log_customer_id;
