--liquibase formatted sql

-- ============================================================================
-- PR #31 - transactional OUTBOX for reliable event publishing to Kafka.
-- ----------------------------------------------------------------------------
-- Writing to Kafka inside the order transaction is impossible (no 2PC with a
-- broker), so instead we write the event HERE, atomically with the order. A
-- polling publisher later forwards PENDING rows to Kafka and marks them
-- PUBLISHED - at-least-once semantics (consumers must be idempotent).
-- ============================================================================

--changeset sushant:31-create-outbox
CREATE TABLE outbox (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(64)  NOT NULL,
    aggregate_id   VARCHAR(64)  NOT NULL,
    event_type     VARCHAR(64)  NOT NULL,
    payload        TEXT         NOT NULL,
    status         VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    attempts       INTEGER      NOT NULL DEFAULT 0,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at   TIMESTAMP
);
--rollback DROP TABLE IF EXISTS outbox;

--changeset sushant:31-index-outbox-status
CREATE INDEX idx_outbox_status_id ON outbox (status, id);
--rollback DROP INDEX IF EXISTS idx_outbox_status_id;
