--liquibase formatted sql

-- ============================================================================
-- PR #48 - MCP tool invocation audit trail (session-scoped authorization).
-- ----------------------------------------------------------------------------
-- Records WHICH agent/principal (OAuth client_id) invoked WHICH MCP tool
-- in WHICH session, with WHAT arguments, and WHETHER it succeeded.
-- The actor column stores the OAuth client_id (or "anonymous" for unauthenticated).
-- The session_id correlates calls within the same MCP initialize/transport session.
-- Arguments are stored as JSON (non-PII) — if a tool needs PII masking, it
-- should scrub before calling the audit service.
-- ============================================================================

--changeset sushant:48-create-mcp-tool-audit
CREATE TABLE mcp_tool_audit (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id      VARCHAR(255)  NOT NULL,
    actor           VARCHAR(255)  NOT NULL,
    tool_name       VARCHAR(128)  NOT NULL,
    arguments_json  TEXT,
    success         BOOLEAN       NOT NULL,
    error_message   TEXT,
    occurred_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--rollback DROP TABLE IF EXISTS mcp_tool_audit;

--changeset sushant:48-index-mcp-tool-audit-session
CREATE INDEX idx_mcp_tool_audit_session_id ON mcp_tool_audit (session_id);
--rollback DROP INDEX IF EXISTS idx_mcp_tool_audit_session_id;

--changeset sushant:48-index-mcp-tool-audit-actor
CREATE INDEX idx_mcp_tool_audit_actor ON mcp_tool_audit (actor);
--rollback DROP INDEX IF EXISTS idx_mcp_tool_audit_actor;

--changeset sushant:48-index-mcp-tool-audit-tool
CREATE INDEX idx_mcp_tool_audit_tool_name ON mcp_tool_audit (tool_name);
--rollback DROP INDEX IF EXISTS idx_mcp_tool_audit_tool_name;