package com.company.orderapi.domain;

import jakarta.persistence.Column;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import jakarta.persistence.Version;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDateTime;

/**
 * Base class for every JPA entity (PR #3).
 *
 * <p>The single {@code id} lives here so all entities share one convention.
 * Generation matches the Liquibase schema from PR #2: every table uses
 * {@code BIGINT GENERATED BY DEFAULT AS IDENTITY}, i.e. Hibernate must use
 * {@link GenerationType#IDENTITY} - never a sequence.
 *
 * <p>PR #8: the {@code @Version} field also lives here, giving EVERY entity
 * optimistic locking with one declaration. The matching {@code version} column
 * was added to all 8 tables by the PR #8 Liquibase changeset. On each UPDATE
 * Hibernate increments {@code version} and adds
 * {@code WHERE version = <value it read>}; if the row changed concurrently, 0
 * rows match and Hibernate throws an optimistic-lock exception - no lost
 * updates.
 *
 * <p>equals/hashCode are deliberately NOT overridden yet: ids are only assigned
 * at flush time, which makes id-based equality unsafe for transient objects.
 * Object identity is correct within one persistence context; a later PR
 * (entities in Sets / merging) revisits this topic.
 */
@MappedSuperclass
@EntityListeners(AuditingEntityListener.class)
public abstract class BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Version
    @Column(name = "version", nullable = false)
    private long version;

    // --- PR #10: auditing (populated by AuditingEntityListener, see below) ---

    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @CreatedBy
    @Column(name = "created_by", nullable = false, updatable = false, length = 64)
    private String createdBy;

    @LastModifiedBy
    @Column(name = "updated_by", nullable = false, length = 64)
    private String updatedBy;

    protected BaseEntity() {
        // No-arg constructor required by JPA/Hibernate for instantiation.
    }

    public Long getId() {
        return id;
    }

    public long getVersion() {
        return version;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public String getUpdatedBy() {
        return updatedBy;
    }

    // No public setId()/setVersion(): the database owns id generation, and
    // Hibernate manages the version counter itself. Audit fields are owned by
    // the AuditingEntityListener and have no setters either.
}
