package com.company.orderapi.domain;

import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;

/**
 * Base class for every JPA entity (PR #3).
 *
 * <p>The single {@code id} lives here so all entities share one convention.
 * Generation matches the Liquibase schema from PR #2: every table uses
 * {@code BIGINT GENERATED BY DEFAULT AS IDENTITY}, i.e. Hibernate must use
 * {@link GenerationType#IDENTITY} - never a sequence.
 *
 * <p>equals/hashCode are deliberately NOT overridden yet: ids are only assigned
 * at flush time, which makes id-based equality unsafe for transient objects.
 * Object identity is correct within one persistence context; a later PR
 * (entities in Sets / merging) revisits this topic.
 */
@MappedSuperclass
public abstract class BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    protected BaseEntity() {
        // No-arg constructor required by JPA/Hibernate for instantiation.
    }

    public Long getId() {
        return id;
    }

    // No public setId(): the database owns id generation. Tests and code use
    // the returned id after flush() instead.
}
