package com.company.orderapi.domain;

import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import jakarta.persistence.Version;

/**
 * Base class for every JPA entity (PR #3).
 *
 * <p>The single {@code id} lives here so all entities share one convention.
 * Generation matches the Liquibase schema from PR #2: every table uses
 * {@code BIGINT GENERATED BY DEFAULT AS IDENTITY}, i.e. Hibernate must use
 * {@link GenerationType#IDENTITY} - never a sequence.
 *
 * <p>PR #8: the {@code @Version} field also lives here, giving EVERY entity
 * optimistic locking with one declaration. The matching {@code version} column
 * was added to all 8 tables by the PR #8 Liquibase changeset. On each UPDATE
 * Hibernate increments {@code version} and adds
 * {@code WHERE version = <value it read>}; if the row changed concurrently, 0
 * rows match and Hibernate throws an optimistic-lock exception - no lost
 * updates.
 *
 * <p>equals/hashCode are deliberately NOT overridden yet: ids are only assigned
 * at flush time, which makes id-based equality unsafe for transient objects.
 * Object identity is correct within one persistence context; a later PR
 * (entities in Sets / merging) revisits this topic.
 */
@MappedSuperclass
public abstract class BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Version
    @Column(name = "version", nullable = false)
    private long version;

    protected BaseEntity() {
        // No-arg constructor required by JPA/Hibernate for instantiation.
    }

    public Long getId() {
        return id;
    }

    public long getVersion() {
        return version;
    }

    // No public setId()/setVersion(): the database owns id generation, and
    // Hibernate manages the version counter itself.
}
